name: SSH-Linux
on:
  watch:
    types: started
jobs:
  SSH:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4      
      - name: Use system Python
        run: echo "Using $(python --version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: SSH connection to Actions
        run: |
            python -m tmate --wait-timeout=600
